db.url=jdbc:mysql://localhost:3306/trackpackdb
db.user=root
db.password=

# MODERATION: Clé API OpenAI pour le service de modération automatique
openai.api.key=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

# RESUME IA: Cl\u00e9 API Google Gemini pour le service de r\u00e9sum\u00e9
gemini.api.key=AIzaSyDR-Gc08Hn0fPupjBCc83RN2RlDMvL_6NA



